receivers:
  # Collect own metrics
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 10s
        file_sd_configs:
        - files:
          - 'targets.json'

processors:
  batch:

exporters:
  otlphttp:
    endpoint: http://data-counter:8090/otelcol/with-compression
  otlphttp/nocompress:
    endpoint: http://data-counter:8090/otelcol/without-compression
    compression: none
  prometheusremotewrite:
    endpoint: http://data-counter:8090/otelcol/prw

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [otlphttp, otlphttp/nocompress, prometheusremotewrite]